#!/usr/bin/env python3
"""Create a real bootable Debian-based live OS ISO from Linux, macOS, or Windows.

The heavy lifting is done by Debian's own ``live-build`` tooling, either inside a
Debian Docker container (the default, works on every platform) or with natively
installed ``live-build`` packages (Linux only, needs root).  This module prepares
the build context, invokes the builder, and copies the resulting ISO -- together
with a SHA-256 checksum and the full build log -- into the output directory.

It never touches the host operating system: everything happens in a scratch
workspace that is removed again unless ``--keep-work`` is used.
"""

from __future__ import annotations

import argparse
import contextlib
import hashlib
import os
import platform
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
import time
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath
from typing import Protocol

__version__ = "2.0.0"

# Debian suites that publish a ``debian:<suite>-slim`` container image.
SLIM_RELEASES = ("bookworm", "trixie")
KNOWN_RELEASES = (*SLIM_RELEASES, "forky", "sid")
ARCHITECTURES = ("amd64", "arm64")
KERNEL_BY_ARCHITECTURE = {"amd64": "linux-image-amd64", "arm64": "linux-image-arm64"}
BASE_PACKAGES = ("live-boot", "systemd-sysv", "sudo", "vim-tiny", "less", "network-manager")
COMPRESSIONS = ("xz", "gzip", "zstd", "lz4", "none")
QEMU_BINARY = {"amd64": "qemu-system-x86_64", "arm64": "qemu-system-aarch64"}
# live-build needs a base system, a package cache and an unpacked chroot to fit.
RECOMMENDED_FREE_GIB = 20
PACKAGE_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9+._~-]*(:[A-Za-z0-9]+)?$")
RELEASE_RE = re.compile(r"^[a-z][a-z0-9.-]*$")
# Patterns on the serial console that prove the ISO booted into the live system.
BOOT_MARKERS = ("Debian GNU/Linux", "GNU/Linux", "login:", "live-boot")

STAGING_DIRNAME = "os-maker"
STAGING_SCRIPT_NAME = "apply-staging.sh"
STAGING_SCRIPT = """\
#!/usr/bin/env bash
# Materialise the OS Maker customisation into live-build's config tree.
# Generated by build_os.py; run from the project root, after 'lb config'.
set -euo pipefail
stage="$(cd "$(dirname "$0")" && pwd)"
cd "$(dirname "$stage")"
if [ ! -d config ]; then
    echo "os-maker: no config/ directory here -- run 'lb config' first" >&2
    exit 1
fi
mkdir -p config/package-lists config/includes.chroot config/hooks/normal
if [ -f "$stage/packages.txt" ]; then
    {
        echo "# Generated by OS Maker. Edit os-maker/packages.txt instead of this file."
        cat "$stage/packages.txt"
    } > config/package-lists/os-maker.list.chroot
fi
if [ -f "$stage/hostname" ]; then
    mkdir -p config/includes.chroot/etc
    cp "$stage/hostname" config/includes.chroot/etc/hostname
fi
if [ -d "$stage/includes.chroot" ]; then
    cp -a "$stage/includes.chroot/." config/includes.chroot/
fi
if compgen -G "$stage/hooks/*.hook.chroot" > /dev/null; then
    cp "$stage"/hooks/*.hook.chroot config/hooks/normal/
    chmod +x config/hooks/normal/*.hook.chroot
fi
echo "os-maker: customisation applied to config/"
"""


class BuildError(RuntimeError):
    """A user-facing problem that stops the build (bad input, missing ISO, ...)."""


@dataclass
class CommandResult:
    """Outcome of a streamed subprocess run: exit code plus its last output lines."""

    returncode: int
    tail: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.returncode == 0


def colour_supported() -> bool:
    return sys.stdout.isatty() and os.environ.get("TERM", "") != "dumb" and not os.environ.get("NO_COLOR")


def print_step(message: str) -> None:
    prefix = "\033[1;36m==> \033[0m" if colour_supported() else "==> "
    print(f"\n{prefix}{message}", flush=True)


def print_warning(message: str) -> None:
    colour = sys.stderr.isatty() and not os.environ.get("NO_COLOR")
    label = "\033[1;33mos-maker: warning:\033[0m" if colour else "os-maker: warning:"
    print(f"{label} {message}", file=sys.stderr, flush=True)


def default_packages(architecture: str) -> list[str]:
    """Packages for ``architecture``: the matching kernel plus a small live base."""
    try:
        kernel = KERNEL_BY_ARCHITECTURE[architecture]
    except KeyError:  # pragma: no cover - argparse restricts the choices
        raise BuildError(f"unsupported architecture {architecture!r}") from None
    return [kernel, *BASE_PACKAGES]


def parse_packages(raw: str, architecture: str) -> list[str]:
    """Split a comma separated package list, de-duplicate it and validate each name."""
    packages = list(dict.fromkeys(part.strip() for part in raw.split(",") if part.strip()))
    if not packages:
        raise BuildError("provide at least one package with --packages")
    for package in packages:
        if not PACKAGE_RE.match(package):
            raise BuildError(
                f"invalid package name {package!r} (letters, digits and + . _ ~ - are allowed, "
                "optionally followed by ':architecture')"
            )
    for package in packages:
        match = re.fullmatch(r"linux-image-(\w+)", package)
        if match and match.group(1) != architecture and match.group(1) in ARCHITECTURES:
            raise BuildError(
                f"--packages lists {package} but --architecture is {architecture}; that kernel "
                f"cannot boot the image. Drop it and let OS Maker add {KERNEL_BY_ARCHITECTURE[architecture]}."
            )
    if not any(package.startswith("linux-image-") for package in packages):
        kernel = KERNEL_BY_ARCHITECTURE[architecture]
        print_warning(f"no kernel in --packages; adding {kernel} so the image can boot")
        packages.insert(0, kernel)
    return packages


def sanitize_hostname(name: str) -> str:
    """Turn a display name into something safe for a hostname and a file name."""
    slug = "".join(c if c.isascii() and (c.isalnum() or c == "-") else "-" for c in name.lower())
    slug = re.sub(r"-{2,}", "-", slug).strip("-")
    slug = slug[:64].strip("-")
    return slug[:63].rstrip("-") or "myos"


def parse_copy_spec(spec: str) -> tuple[str, PurePosixPath]:
    """Parse ``SOURCE:DEST-IN-IMAGE``; ``SOURCE`` stays a string so Windows paths work."""
    source, separator, destination = spec.rpartition(":")
    if not separator or not source.strip() or not destination.strip():
        raise BuildError(f"--copy expects SOURCE:DESTINATION, e.g. --copy ./motd:/etc/motd (got {spec!r})")
    target = PurePosixPath(destination.strip())
    if not target.is_absolute() or ".." in target.parts or len(target.parts) < 2:
        raise BuildError(
            f"--copy destination {str(target)!r} must be an absolute path inside the image with at "
            "least one directory level, e.g. /usr/share/backgrounds/wall.png"
        )
    return source.strip(), target


def free_gib(path: Path) -> float | None:
    try:
        return shutil.disk_usage(path).free / 1024**3
    except OSError:
        return None


def native_build_ready() -> tuple[bool, str]:
    """Can live-build run directly on this host? Returns (usable, reason-it-is-not)."""
    if platform.system() != "Linux":
        return False, f"native live-build only runs on Linux (this host is {platform.system()})"
    if shutil.which("lb") is None:
        return False, "live-build is not installed (apt-get install live-build)"
    missing = [tool for tool in ("debootstrap", "xorriso", "mksquashfs") if shutil.which(tool) is None]
    if missing:
        return False, (
            f"missing build tools: {', '.join(missing)} (apt-get install debootstrap xorriso squashfs-tools)"
        )
    if getattr(os, "geteuid", lambda: 1)() != 0:
        return False, "native live-build must run as root (re-run with sudo)"
    return True, ""


def docker_ready() -> tuple[bool, str]:
    """Is a usable Docker daemon available? Returns (usable, version or problem)."""
    if shutil.which("docker") is None:
        return False, "docker was not found on PATH (install Docker Desktop or Docker Engine)"
    try:
        completed = subprocess.run(
            ["docker", "info", "--format", "{{.ServerVersion}}"],
            capture_output=True,
            text=True,
            timeout=90,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return False, f"could not run 'docker info': {exc}"
    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout).strip().splitlines()
        return False, f"the Docker daemon is not reachable ({detail[0] if detail else 'unknown error'})"
    return True, completed.stdout.strip() or "unknown"


def select_build_mode(requested: str, native_usable: bool, docker_usable: bool) -> tuple[str, str]:
    """Pick "native" or "docker" for ``--container``; otherwise ("error", reason)."""
    if requested == "always":
        if not docker_usable:
            return "error", "--container always needs a working Docker daemon"
        return "docker", ""
    if requested == "never":
        if not native_usable:
            return "error", "--container never needs Linux, root privileges and the live-build tools"
        return "native", ""
    if native_usable:
        return "native", ""
    if docker_usable:
        return "docker", ""
    return "error", "neither native live-build nor a usable Docker daemon was found"


def lb_config_command(
    *,
    release: str,
    architecture: str,
    name: str,
    compression: str | None = None,
    with_firmware: bool = False,
) -> list[str]:
    """The ``lb config`` invocation used for both native and containerised builds."""
    command = [
        "lb",
        "config",
        "--distribution",
        release,
        "--architectures",
        architecture,
        "--binary-images",
        "iso-hybrid",
        "--debian-installer",
        "false",
        "--iso-application",
        name,
        "--iso-volume",
        name[:32] or "OSMaker",
    ]
    if with_firmware:
        # Needed by many Wi-Fi/GPU chips; off by default for licensing reasons.
        command += ["--archive-areas", "main contrib non-free-firmware"]
    if compression:
        command += ["--compression", compression]
    return command


def build_image_for(release: str, override: str | None) -> str:
    """Container image whose live-build is new enough to build ``release``."""
    if override:
        return override
    if release in SLIM_RELEASES:
        return f"debian:{release}-slim"
    return f"debian:{SLIM_RELEASES[-1]}-slim"


def docker_setup_script(config_command: Sequence[str]) -> str:
    """The shell script executed inside the build container, in order."""
    return "\n".join(
        [
            "set -eu",
            "export DEBIAN_FRONTEND=noninteractive",
            "apt-get update -o Acquire::Retries=3",
            # Recommends matter here: isolinux, grub-efi and squashfs-tools arrive as
            # recommends and the ISO cannot be generated without them.
            "apt-get install -y live-build debootstrap",
            shlex.join(str(part) for part in config_command),
            f"bash {STAGING_DIRNAME}/{STAGING_SCRIPT_NAME}",
            "lb build",
        ]
    )


def docker_run_command(
    *,
    workspace: Path,
    build_image: str,
    script: str,
    host_architecture: str | None = None,
    target_architecture: str | None = None,
    cache_dir: Path | None = None,
) -> list[str]:
    """Assemble ``docker run`` for the build (bind mounts use POSIX separators for Windows)."""
    command = ["docker", "run", "--rm", "--privileged"]
    if host_architecture and target_architecture and host_architecture != target_architecture:
        command += ["--platform", f"linux/{target_architecture}"]
    mounts = [f"{workspace.as_posix()}:/work"]
    if cache_dir is not None:
        # apt needs its "partial" staging directory to exist under the mount, so it
        # lives inside the shared cache as well.
        (cache_dir / "partial").mkdir(parents=True, exist_ok=True)
        mounts.append(f"{cache_dir.as_posix()}:/var/cache/apt/archives")
        mounts.append(f"{(cache_dir / 'partial').as_posix()}:/var/cache/apt/archives/partial")
    for mount in mounts:
        command += ["-v", mount]
    command += ["-w", "/work/live-os", build_image, "bash", "-lc", script]
    return command


def host_architecture() -> str | None:
    """This machine as a Debian architecture name, or None if unknown."""
    return {"x86_64": "amd64", "amd64": "amd64", "aarch64": "arm64", "arm64": "arm64"}.get(
        platform.machine().lower()
    )


def find_iso(project: Path, not_older_than: float | None = None) -> Path:
    """Newest ISO in ``project``; ``not_older_than`` rejects leftovers from earlier runs."""
    candidates = [path for path in project.glob("*.iso") if path.is_file()]
    if not_older_than is not None:
        fresh = [path for path in candidates if path.stat().st_mtime >= not_older_than]
        if candidates and not fresh:
            raise BuildError(
                "live-build finished but only left ISO(s) from an earlier build ("
                + ", ".join(sorted(path.name for path in candidates))
                + "); no new image was produced"
            )
        candidates = fresh
    if not candidates:
        raise BuildError("live-build completed but produced no ISO")
    return max(candidates, key=lambda path: path.stat().st_mtime)


def sha256_of(path: Path, chunk_size: int = 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(chunk_size), b""):
            digest.update(chunk)
    return digest.hexdigest()


def run(
    command: Sequence[str],
    *,
    cwd: Path | None = None,
    log_path: Path | None = None,
    echo: bool = True,
) -> CommandResult:
    """Stream a command to the console and to ``log_path``, keeping its last lines for errors."""
    line = "$ " + shlex.join(str(part) for part in command)
    if echo:
        print(line, flush=True)
    tail: list[str] = []
    with contextlib.ExitStack() as stack:
        handle = stack.enter_context(Path(log_path).open("a", encoding="utf-8")) if log_path else None
        if handle:
            handle.write(line + "\n")

        def log(text: str) -> None:
            if handle:
                handle.write(text)
                handle.flush()

        process = subprocess.Popen(
            [str(part) for part in command],
            cwd=str(cwd) if cwd else None,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            errors="replace",
        )
        if process.stdout is not None:
            with process.stdout:
                for chunk in process.stdout:
                    sys.stdout.write(chunk)
                    sys.stdout.flush()
                    log(chunk)
                    tail.append(chunk.rstrip("\n"))
                    if len(tail) > 40:
                        tail.pop(0)
    return CommandResult(process.wait(), tail)


class ProcessLike(Protocol):
    """The one thing :func:`wait_for_boot` needs from the QEMU child process."""

    def poll(self) -> int | None: ...


def wait_for_boot(console_log: Path, process: ProcessLike, timeout: float) -> str | None:
    """Poll ``console_log`` for a live-system banner; return the console text or None on timeout."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            text = console_log.read_text(encoding="utf-8", errors="replace")
        except OSError:
            text = ""
        if any(marker in text for marker in BOOT_MARKERS):
            return text
        if process.poll() is not None:
            return None
        time.sleep(0.25)
    return None


def qemu_boot_test(iso: Path, architecture: str, timeout: int, *, log_path: Path | None = None) -> int:
    """Boot the ISO headless in QEMU and check that the live system reaches its console."""
    if architecture != "amd64":
        print_warning(
            f"--boot-test only supports amd64 ISOs ({architecture} images need UEFI firmware, e.g. "
            "QEMU with -bios /usr/share/OVMF/OVMF.fd); skipping the smoke test"
        )
        return 0
    binary = shutil.which(QEMU_BINARY["amd64"])
    if binary is None:
        raise BuildError("qemu-system-x86_64 was not found; install qemu-system-x86 to use --boot-test")
    with tempfile.TemporaryDirectory(prefix="os-maker-boot-") as scratch:
        console_log = Path(scratch) / "console.log"
        command = [
            binary,
            "-name",
            "os-maker-boot-test",
            "-m",
            "2048",
            "-machine",
            "q35,accel=kvm:tcg",
            "-cdrom",
            str(iso),
            "-boot",
            "d",
            "-display",
            "none",
            "-serial",
            f"file:{console_log.as_posix()}",
            "-monitor",
            "none",
            "-no-reboot",
        ]
        print_step(f"Booting {iso.name} in QEMU for up to {timeout}s")
        if log_path:
            with Path(log_path).open("a", encoding="utf-8") as handle:
                handle.write("$ " + shlex.join(command) + "\n")
        process = subprocess.Popen(command, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        try:
            console = wait_for_boot(console_log, process, timeout)
        finally:
            process.terminate()
            with contextlib.suppress(subprocess.TimeoutExpired):
                process.wait(timeout=15)
            process.kill()
        text = console_log.read_text(encoding="utf-8", errors="replace") if console_log.exists() else ""
        if log_path:
            with Path(log_path).open("a", encoding="utf-8") as handle:
                handle.write(text)
        if console is not None:
            print("Boot test passed: the image reached the live system (login prompt detected).")
            return 0
        if not text.strip():
            print_warning("QEMU produced no console output; the ISO may not be bootable at all")
        raise BuildError("boot test failed: no live-system banner appeared on the QEMU console")


def stage_project(
    project: Path,
    *,
    packages: Sequence[str],
    hostname: str,
    copies: Sequence[tuple[str, PurePosixPath]],
    hooks: Sequence[Path],
) -> list[str]:
    """Write the ``os-maker/`` staging tree that ``apply-staging.sh`` folds into ``config/``."""
    staging = project / STAGING_DIRNAME
    hooks_dir = staging / "hooks"
    staging.mkdir(parents=True, exist_ok=True)
    hooks_dir.mkdir(parents=True, exist_ok=True)
    notes: list[str] = []
    (staging / "packages.txt").write_text("\n".join(packages) + "\n", encoding="utf-8")
    (staging / "hostname").write_text(hostname + "\n", encoding="utf-8")
    script = staging / STAGING_SCRIPT_NAME
    script.write_text(STAGING_SCRIPT, encoding="utf-8")
    script.chmod(0o755)
    notes.append(f"{len(packages)} packages -> os-maker/packages.txt")
    notes.append(f"hostname {hostname!r} -> /etc/hostname")
    for number, hook in enumerate(hooks, start=1):
        if not hook.is_file():
            raise BuildError(f"--hook file not found: {hook.resolve()}")
        target = hooks_dir / f"{number:04d}-os-maker.hook.chroot"
        shutil.copy2(hook, target)
        target.chmod(0o755)
        notes.append(f"hook {hook.name} -> config/hooks/normal/{target.name}")
    for source, destination in copies:
        src = Path(source).expanduser()
        if not src.exists():
            raise BuildError(f"--copy source not found: {src}")
        relative = destination.parts[1:]
        target = staging / "includes.chroot" / Path(*relative)
        if src.is_dir():
            shutil.copytree(src, target, dirs_exist_ok=True)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, target)
        notes.append(f"copy {source} -> {destination}")
    return notes


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="build_os.py",
        description="Create a bootable Debian-based live OS ISO (Linux, macOS and Windows).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "examples:\n"
            "  python3 build_os.py --name MyOS\n"
            "  python3 build_os.py --name StudyOS --release trixie --packages sudo,neofetch,xfce4\n"
            "  python3 build_os.py --compression zstd --cache-dir ~/.cache/os-maker/apt --boot-test\n"
        ),
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")

    customise = parser.add_argument_group("customising the OS")
    customise.add_argument("--name", default="MyOS", help="OS display name (ISO label and hostname)")
    customise.add_argument(
        "--release",
        default="bookworm",
        metavar="SUITE",
        help=f"Debian suite (known: {', '.join(KNOWN_RELEASES)})",
    )
    customise.add_argument(
        "--architecture", default="amd64", choices=ARCHITECTURES, help="target CPU architecture"
    )
    customise.add_argument(
        "--packages",
        metavar="LIST",
        help=f"comma separated packages (default: the kernel for --architecture + {', '.join(BASE_PACKAGES)})",
    )
    customise.add_argument(
        "--copy",
        action="append",
        default=[],
        metavar="SRC:DEST",
        help="copy a file or directory into the image, e.g. --copy ./wall.png:/usr/share/backgrounds/wall.png "
        "(repeatable)",
    )
    customise.add_argument(
        "--hook",
        action="append",
        type=Path,
        default=[],
        metavar="FILE",
        help="live-build chroot hook script (repeatable)",
    )
    customise.add_argument(
        "--with-firmware",
        action="store_true",
        help="enable the non-free-firmware archive area (Wi-Fi/GPU firmware)",
    )
    customise.add_argument(
        "--compression",
        choices=COMPRESSIONS,
        help="squashfs compression; zstd/lz4 build much faster, xz is smaller",
    )

    where = parser.add_argument_group("where things live")
    where.add_argument(
        "--output",
        type=Path,
        default=Path("dist"),
        metavar="DIR",
        help="directory for the finished ISO (default: ./dist)",
    )
    where.add_argument(
        "--work-dir", type=Path, metavar="DIR", help="build in this directory instead of a temporary one"
    )
    where.add_argument("--keep-work", action="store_true", help="keep the workspace after the build")
    where.add_argument("--no-log", action="store_true", help="do not write a build log next to the ISO")

    engine = parser.add_argument_group("build engine")
    engine.add_argument(
        "--container",
        choices=("auto", "always", "never"),
        default="auto",
        help="build in Docker (auto: use native live-build on Linux when it is usable)",
    )
    engine.add_argument(
        "--build-image",
        metavar="IMAGE",
        help=f"Docker image providing the build tools (default: debian:<release>-slim, else debian:{SLIM_RELEASES[-1]}-slim)",
    )
    engine.add_argument(
        "--cache-dir",
        type=Path,
        metavar="DIR",
        help="reuse this directory as the container's apt cache to speed up rebuilds",
    )
    engine.add_argument(
        "--skip-checks", action="store_true", help="skip the up-front Docker/disk-space checks"
    )

    testing = parser.add_argument_group("verification")
    testing.add_argument(
        "--boot-test", action="store_true", help="boot the ISO headless in QEMU and look for a login prompt"
    )
    testing.add_argument(
        "--boot-timeout",
        type=int,
        default=300,
        metavar="SECONDS",
        help="seconds to wait during --boot-test (default: 300)",
    )
    testing.add_argument(
        "--dry-run", action="store_true", help="print the plan and the commands without running anything"
    )
    testing.add_argument(
        "-q", "--quiet", action="store_true", help="do not echo each command before running it"
    )
    return parser


@dataclass(frozen=True)
class Plan:
    """Everything a build needs, decided before a single command runs."""

    name: str
    hostname: str
    release: str
    architecture: str
    packages: tuple[str, ...]
    copies: tuple[tuple[str, PurePosixPath], ...]
    hooks: tuple[Path, ...]
    compression: str
    with_firmware: bool
    mode: str  # "docker" or "native"
    build_image: str
    daemon: str | None  # Docker version string when a daemon answered
    host_architecture: str | None
    workspace: Path | None  # None means "use a temporary directory"
    output: Path
    destination: Path
    log: bool
    cache_dir: Path | None
    keep_work: bool
    skip_checks: bool
    dry_run: bool
    quiet: bool
    boot_test: bool
    boot_timeout: int

    @property
    def project(self) -> Path:
        """The live-build project directory inside the workspace."""
        root = self.workspace if self.workspace is not None else Path("<temporary workspace>")
        return root / "live-os"

    @property
    def docker_image(self) -> str:
        return build_image_for(self.release, self.build_image)

    def announce(self) -> None:
        """Say how the build will happen, and warn about anything that will make it slow."""
        if self.mode == "docker" and self.daemon:
            print(
                f"Building inside {self.docker_image} via Docker (daemon {self.daemon}); "
                "the host OS is not modified."
            )
        elif self.mode == "docker":
            print(f"Planned build inside {self.docker_image} via Docker (no daemon here yet).")
        else:
            print(
                "Building natively with the installed live-build tooling (this needs root and can take a while)."
            )
        if self.mode == "docker" and self.host_architecture not in (None, self.architecture):
            print_warning(
                f"target architecture {self.architecture} differs from this host ({self.host_architecture}); "
                "the build runs under emulation and can be several times slower"
            )

    def describe(self) -> None:
        """The dry-run report: what *would* happen, in enough detail to review."""
        print_step("Dry run -- nothing was executed")
        print(f"    mode:       {self.mode}")
        print(f"    output ISO: {self.destination}")
        print(f"    packages:   {', '.join(self.packages)}")
        if self.boot_test:
            print(
                f"    boot test:  QEMU smoke test after the build ({self.boot_timeout}s timeout, skipped in a dry run)"
            )
        for source, target in self.copies:
            print(f"    copy:       {source} -> {target}")
        for hook in self.hooks:
            print(f"    hook:       {hook}")
        config = self.config_command()
        if self.mode == "docker":
            print(
                "    docker:     "
                + shlex.join(
                    docker_run_command(
                        workspace=self.workspace
                        if self.workspace is not None
                        else Path("<temporary workspace>"),
                        build_image=self.docker_image,
                        script=docker_setup_script(config),
                        host_architecture=self.host_architecture,
                        target_architecture=self.architecture,
                        cache_dir=self.cache_dir,
                    )
                )
            )
        else:
            print(
                "    commands:   "
                + " && ".join(
                    [shlex.join(config), f"bash {STAGING_DIRNAME}/{STAGING_SCRIPT_NAME}", "lb build"]
                )
            )

    def config_command(self) -> list[str]:
        return lb_config_command(
            release=self.release,
            architecture=self.architecture,
            name=self.name,
            compression=self.compression,
            with_firmware=self.with_firmware,
        )


def decide(args: argparse.Namespace) -> Plan:
    """Turn parsed arguments into a :class:`Plan`, rejecting bad ones before any work.

    Raises :class:`BuildError` with the exit code 2 convention of the CLI: the whole
    point is to fail on a typo rather than after a twenty-minute build.
    """
    name = args.name.strip()
    if not name or any(char in name for char in "\r\n\0"):
        raise BuildError("--name must be a non-empty, single-line name")
    if not RELEASE_RE.match(args.release):
        raise BuildError(f"invalid --release {args.release!r}")
    if args.release not in KNOWN_RELEASES:
        print_warning(
            f"{args.release!r} is not a known Debian suite ({', '.join(KNOWN_RELEASES)}); live-build may reject it"
        )
    if args.boot_timeout <= 0:
        raise BuildError("--boot-timeout must be a positive number of seconds")
    if args.cache_dir is not None and args.container == "never":
        raise BuildError("--cache-dir only applies to Docker builds")

    try:
        packages = (
            parse_packages(args.packages, args.architecture)
            if args.packages
            else default_packages(args.architecture)
        )
        copies = tuple(parse_copy_spec(spec) for spec in args.copy)
    except BuildError as exc:
        raise BuildError(str(exc)) from None

    mode, daemon = select_engine(args)
    output = args.output.resolve()
    return Plan(
        name=name,
        hostname=sanitize_hostname(name),
        release=args.release,
        architecture=args.architecture,
        packages=tuple(packages),
        copies=copies,
        hooks=tuple(args.hook),
        compression=args.compression,
        with_firmware=args.with_firmware,
        mode=mode,
        build_image=args.build_image,
        daemon=daemon,
        host_architecture=host_architecture(),
        workspace=args.work_dir.expanduser().resolve() if args.work_dir else None,
        output=output,
        destination=output / f"{sanitize_hostname(name)}-{args.release}-{args.architecture}.iso",
        log=not args.no_log,
        cache_dir=args.cache_dir.expanduser().resolve() if args.cache_dir else None,
        keep_work=args.keep_work,
        skip_checks=args.skip_checks,
        dry_run=args.dry_run,
        quiet=args.quiet,
        boot_test=args.boot_test,
        boot_timeout=args.boot_timeout,
    )


def select_engine(args: argparse.Namespace) -> tuple[str, str | None]:
    """Which engine will build this image, and how we know (daemon version when it answered)."""
    """Pick ``docker`` or ``native``, explaining why neither works when that is the answer."""
    native_usable, native_problem = native_build_ready()
    docker_usable, docker_detail = docker_ready()
    mode, problem = select_build_mode(args.container, native_usable, docker_usable)
    if mode == "error" and args.dry_run:
        print_warning(f"{problem}; showing the plan anyway (assuming a Docker build)")
        return "docker", None
    if mode == "error":
        lines = [
            f"{problem}.",
            f"    native live-build: {native_problem or 'ready'}",
            f"    docker: {docker_detail if not docker_usable else 'ready (' + docker_detail + ')'}",
        ]
        if not docker_usable and args.container != "never":
            lines.append(
                "    hint: install Docker Desktop (Windows/macOS) or Docker Engine (Linux), start it, then retry"
            )
        raise BuildError("\n".join(lines))
    return mode, docker_detail if (mode == "docker" and docker_usable) else None


def check_free_space(plan: Plan) -> None:
    """Warn early: a live build that runs out of disk fails late and messily."""
    hint = plan.workspace if plan.workspace is not None else Path(tempfile.gettempdir())
    while not hint.exists() and hint != hint.parent:
        hint = hint.parent  # the first existing ancestor is what has to hold the data
    if plan.skip_checks:
        return
    free = free_gib(hint)
    if free is None or free >= RECOMMENDED_FREE_GIB:
        return
    print_warning(
        f"only {free:.1f} GiB free where the workspace lives; a live build usually needs "
        f">= {RECOMMENDED_FREE_GIB} GiB. Use --work-dir to build somewhere with more space."
    )


@dataclass
class Workspace:
    """The directory a build happens in, and the rules for cleaning it up."""

    root: Path
    temporary: bool
    keep: bool
    log: bool
    log_path: Path | None = None

    @property
    def project(self) -> Path:
        return self.root / "live-os"

    @classmethod
    def create(cls, plan: Plan) -> Workspace:
        if plan.workspace is not None:
            plan.workspace.mkdir(parents=True, exist_ok=True)
            workspace = cls(root=plan.workspace, temporary=False, keep=plan.keep_work, log=plan.log)
        else:
            workspace = cls(
                root=Path(tempfile.mkdtemp(prefix="os-maker-")).resolve(),
                temporary=True,
                keep=plan.keep_work,
                log=plan.log,
            )
        workspace.project.mkdir(parents=True, exist_ok=True)
        for stale in workspace.project.glob("*.iso"):
            stale.unlink()  # never ship an ISO from a previous run
        workspace.log_path = workspace.root / "build.log" if workspace.log else None
        if workspace.log_path is not None:
            workspace.log_path.parent.mkdir(parents=True, exist_ok=True)
        return workspace

    def close(self) -> None:
        """Keep the workspace when asked; otherwise drop only what we created ourselves."""
        if self.keep:
            print(f"Build workspace kept at: {self.project}")
        elif self.temporary:  # never delete a directory the user pointed us at
            shutil.rmtree(self.root, ignore_errors=True)


def stage(workspace: Workspace, plan: Plan) -> None:
    """Write the os-maker staging directory and clear it out of the way of ``lb``."""
    print_step(f"Preparing build context in {workspace.project}")
    for note in stage_project(
        workspace.project,
        packages=list(plan.packages),
        hostname=plan.hostname,
        copies=list(plan.copies),
        hooks=list(plan.hooks),
    ):
        print(f"    + {note}")


def execute(workspace: Workspace, plan: Plan) -> CommandResult:
    """Run the build itself, streaming its output and log."""
    echo = not plan.quiet
    config_command = plan.config_command()
    if plan.mode == "native":
        result = run(config_command, cwd=workspace.project, log_path=workspace.log_path, echo=echo)
        if not result.ok:
            raise BuildError(
                f"lb config failed (exit code {result.returncode}):\n    " + "\n    ".join(result.tail[-5:])
            )
        run(
            ["bash", f"{STAGING_DIRNAME}/{STAGING_SCRIPT_NAME}"],
            cwd=workspace.project,
            log_path=workspace.log_path,
            echo=echo,
        )
        return run(["lb", "build"], cwd=workspace.project, log_path=workspace.log_path, echo=echo)
    return run(
        docker_run_command(
            workspace=workspace.root,
            build_image=plan.docker_image,
            script=docker_setup_script(config_command),
            host_architecture=plan.host_architecture,
            target_architecture=plan.architecture,
            cache_dir=plan.cache_dir,
        ),
        cwd=workspace.root,
        log_path=workspace.log_path,
        echo=echo,
    )


def collect(workspace: Workspace, plan: Plan, iso: Path, digest: str) -> None:
    """Put the ISO, its checksum and the log next to each other in the output directory."""
    shutil.copy2(iso, plan.destination)
    plan.destination.with_suffix(plan.destination.suffix + ".sha256").write_text(
        f"{digest}  {plan.destination.name}\n", encoding="utf-8"
    )
    if workspace.log_path is not None and workspace.log_path.is_file():
        shutil.copy2(workspace.log_path, plan.destination.with_suffix(plan.destination.suffix + ".log"))


def report(plan: Plan, digest: str) -> None:
    size_gib = plan.destination.stat().st_size / 1024**3
    tick = "\033[1;32m" if colour_supported() else ""
    reset = "\033[0m" if tick else ""
    print(f"\n{tick}Bootable ISO created:{reset} {plan.destination} ({size_gib:.2f} GiB)")
    print(f"SHA-256: {digest}")
    print("Test it in a virtual machine before writing it to hardware, e.g.:")
    print(f"    qemu-system-x86_64 -cdrom {plan.destination.name} -m 2048 -boot d")
    print(
        "Write it to a USB stick with balenaEtcher, Rufus, or: dd if=<iso> of=/dev/sdX bs=4M status=progress"
    )


def run_build(plan: Plan) -> int:
    """The whole build, from an empty workspace to a finished ISO."""
    plan.output.mkdir(parents=True, exist_ok=True)
    workspace = Workspace.create(plan)
    try:
        stage(workspace, plan)
        # mtime can be truncated to whole seconds on some filesystems, so give the
        # "is this ISO fresh?" check a little grace (stale ISOs were deleted above).
        build_started = time.time() - 2
        result = execute(workspace, plan)
        if not result.ok:
            raise BuildError(
                f"build failed (exit code {result.returncode}):\n    " + "\n    ".join(result.tail[-15:])
            )
        print_step("Collecting the image")
        iso = find_iso(workspace.project, not_older_than=build_started)
        digest = sha256_of(iso)
        collect(workspace, plan, iso, digest)
        if (
            plan.mode == "docker"
            and plan.workspace is not None
            and platform.system() == "Linux"
            and getattr(os, "geteuid", lambda: 0)() != 0
        ):
            print_warning(
                f"files in {workspace.root} were created by root inside the container; "
                f"clean them up with: sudo rm -rf {workspace.project}"
            )
        report(plan, digest)
        if plan.boot_test:
            return qemu_boot_test(
                plan.destination, plan.architecture, plan.boot_timeout, log_path=workspace.log_path
            )
        return 0
    finally:
        workspace.close()


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        plan = decide(args)
    except BuildError as exc:
        print(f"os-maker: {exc}", file=sys.stderr)
        return 2

    plan.announce()
    check_free_space(plan)
    if plan.dry_run:
        plan.describe()
        return 0
    try:
        return run_build(plan)
    except BuildError as exc:
        print(f"os-maker: {exc}", file=sys.stderr)
        if plan.workspace is None and not plan.keep_work:
            print(
                "os-maker: the workspace was deleted; re-run with --keep-work to inspect it", file=sys.stderr
            )
        return 1
    except KeyboardInterrupt:
        print("\nos-maker: interrupted", file=sys.stderr)
        return 130
    except OSError as exc:
        print(f"os-maker: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
